export { ReactComponent as IconEyeOpen } from "./eyeOpen.svg";
export { ReactComponent as IconSpinner } from "./spinner.svg";
export { ReactComponent as IconAdd } from "./add.svg";
export { ReactComponent as IconGrid } from "./list.svg";
export { ReactComponent as IconList } from "./grid.svg";
export { ReactComponent as IconDelete } from "./delete.svg";
export { ReactComponent as IconCheck } from "./check.svg";
export { ReactComponent as IconUser } from "./user.svg";
export { ReactComponent as IconAngleDown } from "./angledown.svg";
